name: Daily US Stock

on:
  schedule:
    - cron: '30 21 * * 1-5' # 美股收盤後，台灣/香港時間大約早上 5:30 執行
  workflow_dispatch: # 允許我們等下手動點擊測試

jobs:
  run-system:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: pip install -r requirements.txt
    - env:
        # 把 GitHub 密碼庫的 BARK_KEY 拿出來給 Python 用
        BARK_KEY: ${{ secrets.BARK_KEY }}
      run: python main.py
